name: Backend CD - Deploy to AKS

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  RESOURCE_GROUP: sit722-rg
  AKS_CLUSTER: maazkahn-aks
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  deploy_backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER }}

      - name: Set Kubernetes context
        run: kubectl config current-context

      - name: Deploy Product Service
        run: |
          kubectl set image deployment/product-service product-service=${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.IMAGE_TAG }} || \
          kubectl apply -f k8s/backend/product_service_deployment.yaml

      - name: Deploy Order Service
        run: |
          kubectl set image deployment/order-service order-service=${{ env.ACR_LOGIN_SERVER }}/order_service:${{ env.IMAGE_TAG }} || \
          kubectl apply -f k8s/backend/order_service_deployment.yaml

      - name: Verify deployments
        run: kubectl rollout status deployment/product-service && kubectl rollout status deployment/order-service

      - name: Logout from Azure
        if: always()
        run: az logout
