name: Frontend CD - Deploy to AKS

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  RESOURCE_GROUP: sit722-rg
  AKS_CLUSTER: maazkahn-aks
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER }}

      - name: Set Kubernetes context
        run: kubectl config current-context

      - name: Deploy Frontend Service
        run: |
          kubectl set image deployment/frontend frontend=${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }} || \
          kubectl apply -f k8s/frontend/frontend_deployment.yaml

      - name: Verify deployment
        run: kubectl rollout status deployment/frontend

      - name: Logout from Azure
        if: always()
        run: az logout
